MedicalProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('auth_app.urls')),
    path('', include('patient_app.urls')),
]

auth_app/urls.py
from django.urls import path
from . import views

app_name = 'auth_app'
urlpatterns = [
    path('register/', views.patient_registration, name='registration'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

patient_app/urls.py
from django.urls import path
from . import views


app_name = 'patient_app'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('patient/patient-data-entry/', views.patient_data_enter_view, name='data_entry'),
    path('patient/dashboard/', views.patient_dashboard, name='dashboard'),
]

patient_app/models.py
from django.db import models
from auth_app.models import User


class PatientHealthModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hb = models.IntegerField(verbose_name='Heart Beat')
    weight = models.IntegerField()
    sleep_time = models.TimeField()
    date = models.DateTimeField(auto_now_add=True)
    

patient_app/forms.py
from django import forms
from django.core.exceptions import ValidationError


class PatientDataForm(forms.Form):
    hb = forms.IntegerField()
    weight = forms.IntegerField()
    sleep_time = forms.TimeField()

    def clean_sleep_time(self):
        sleep_time = self.cleaned_data['sleep_time']
        if sleep_time.hour >= 24:
            raise ValidationError("Sleep time can't be greater than 24 hours.")
        return sleep_time
    

patient_app/views.py
from django.shortcuts import render
import pandas as pd
from .models import PatientHealthModel
from .forms import PatientDataForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
from datetime import datetime
from .ml_model import MLModel
from MedicalProject.settings import BASE_DIR
from .utils import cleaning_latest_record
import numpy as np


def index(request):
    return render(request, 'patient_app/index.html')


@login_required(login_url=reverse_lazy('auth_app:login'))
def patient_data_enter_view(request):
    if request.method == "POST":
        form = PatientDataForm(request.POST)
        if form.is_valid():
            user = request.user
            PatientHealthModel.objects.create(**{'user':user, **form.cleaned_data})
            return redirect(reverse('patient_app:dashboard'))
        else:
            return render(request, 'patient_app/patient_data_form.html', {'form':form})
    form = PatientDataForm()
    return render(request, 'patient_app/patient_data_form.html', {'form':form})


@login_required(login_url=reverse_lazy('auth_app:login'))
def patient_dashboard(request):
    # getting the active user
    user = request.user
    # Extracting the PatientHealthModel Data of that particular user
    patient_data = PatientHealthModel.objects.filter(user=user)

    
    # checking whether the user has PatientHealthModel data or not if not displaying the dashboard with out any data
    if not patient_data.exists():
        return render(request, 'patient_app/dashboard.html', {'rating':0})
    
    
    # columns for pandas data frame
    columns = ['hb', 'sleep_time', 'date', 'weight']
    df = pd.DataFrame(patient_data.values_list('hb', 'sleep_time', 'date', 'weight'), columns=columns)
    
    # sorting values to remove the old records of that particular day
    df.sort_values(by='date', ascending=True)
    # after sorting changing the date as per our requirement
    df['date'] = [ x.date() for x in df['date']]

    # removing the old records of that particular day
    df = df.drop_duplicates(subset='date') 
    
    # finding the latest record
    df_latest_record = df.tail(1)

    x = df_latest_record.to_dict()
    
    # converting it into dict
    latest_record = cleaning_latest_record(x)
    
    # age of the person
    age = datetime.today().year - request.user.dob.year
    
    # Define the the path to your model file
    model_path = BASE_DIR/'ml_models'/'project_model.h5'

    # creating the MLModel object
    ml_model_prediction = MLModel(model_path=model_path)
    
    # input data to the MLModel
    # inputs are => heart_beat, BMI, gender, sleep time, age
    input_data = np.array([[
        latest_record['hb'],
        int(latest_record['weight']/((user.height/100)**2)),
        1 if user.gender == 'M' else 0,
        latest_record['sleep_time'].hour,
        age
    ]])
    
    # prediction determined by the Machine Learning Model
    rating_prediction = ml_model_prediction.predict(input_data)
    rating = np.argmax(rating_prediction) + 1

    # converting sleep time into hours for displaying in charts
    df['sleep_time'] = [x.hour for x in df['sleep_time'] ]
        
    return render(request, 'patient_app/dashboard.html', {'data': df.to_json(orient='records', date_format='iso'), 'rating':rating})

patient_app/templates/patient_app/dashboard.html
{% extends 'base.html' %}

{% block body %}
    <div class="container mt-3">
        {% if data %}
            <div class="row justify-content-center">
                <div class="col-md-6 text-white align-items-center">
                    <div class="d-flex align-items-center">
                        <span class="mr-2">
                            Your health status : 
                        </span>
                        <div class="rating text-gold">
                            {% for i in "*****" %}
                                {% if forloop.counter >= rating %}
                                    <span style="font-size: 50px;">&#9733;</span> <!-- Filled star -->
                                {% else %}
                                    <span style="font-size: 50px;">&#9734;</span> <!-- Empty star -->
                                {% endif %}
                            {% endfor %} 
                        </div>
                    </div>
                    
                </div>
            </div>
            <div class="row justify-content-center align-items-center h-20">
                <div class="col-md-6 col-sm-12"><canvas id="hbChart" class="h-100 w-100" ></canvas></div>
                <div class="col-md-6 col-sm-12"><canvas id="sleepChart"  class="h-100 w-100"></canvas></div>
                <div class="col-md-6 col-sm-12"><canvas id="weightChart"  class="h-100 w-100"></canvas></div>
            
            </div>
        {% else %}
            <div class="row h-30 justify-content-center align-items-center">
                <div class="col-md-6 h3">
                    Patient health data not available.
                </div>
            </div>
        {% endif %}
        <script>

            // get data drom th django template
            var healthReports = JSON.parse('{{data|escapejs}}');

            if (!Array.isArray(healthReports)) {
                // Handle error gracefully
                console.error("Invalid health report data");
            }

            // extract necessary data for the charts
            const labels = healthReports.map(report => new Date(report.date).toLocaleDateString());
            const hbData = healthReports.map(report => report.hb);
            const sleepTimeData = healthReports.map(report=>report.sleep_time);
            const weightData = healthReports.map(report=>report.weight);

            // construct the data object for chart.js
            function createBarChart(canvasId, label, data) {
            var ctx = document.getElementById(canvasId).getContext('2d');
            var chart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: labels,
                    datasets: [{
                        label: label,
                        data: data,
                        backgroundColor: 'rgba(54, 162, 235, 0.6)',
                        borderColor: 'rgba(54, 162, 235, 1)',
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        y:{
                             beginAtZero: true
                        }   
                    }
                }
            });
        }

            // create bar charts
            createBarChart('hbChart', 'Heart Beat', hbData);
            createBarChart('weightChart', 'Weight', weightData);
            createBarChart('sleepChart', 'Sleep Time', sleepTimeData);

        </script>
    </div>
{% endblock %}

patient_app/templates/patient_app/index.html
{% extends 'base.html' %}



{% block body %}
    <div class="container">
        {% if user.is_authenticated %}
            <div class="row justify-content-evenly">
                <div class="col-md-3">
                    <a href="{% url 'patient_app:data_entry' %}" class="btn btn-primary">Click here to enter the health data</a>
                </div>
                <div class="col-md-3 align-self-end">
                    <a href="{% url 'patient_app:dashboard' %}" class="btn btn-success">Dashboard</a>
                </div>
            </div>
        {% else %}
            <div class="row justify-content-center align-items-center h-20">
                <div class="col-md-6 h2">
                    Please log in to view the Health Reports.
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

patient_app/templates/patient_app/patient_data_form.html
{% extends 'base.html' %}

{% block body %}
    <div class="container mt-3">
        <div class="row justify-content-center align-items-center h-30">
            <div class="col-md-5">
                <form method="post">
                    {% csrf_token %}
                    <fieldset>
                        <legend>Enter health data</legend>
                        {% if form.hb.errors %}
                            {{form.hb.errors}}
                        {% endif %}
                        <div class="mb-3">
                            <label for="id_hb" class="form-label">Heart Beat</label>
                            <input type="number" name="hb" placeholder="heart beat count for 1 minute" id="id_hb" class="form-control mb-2">
                        </div>
                        {% if form.weight.errors %}
                            {{form.weight.errors}}
                        {% endif %}
                        <div class="mb-3">
                            <label for="id_weight" class="form-label">Weight</label>
                            <input type="number" name="weight" placeholder="Enter your weight" id="id_weight" class="form-control mb-2">
                        </div>
                        {% if form.sleep_time.errors %}
                            {{form.sleep_time.errors}}
                        {% endif %}
                        <div class="mb-3">
                            <label for="id_sleep_time" class="form-label">Sleep Time</label>
                            <input type="time" name="sleep_time"  id="id_sleep_time" class="form-control mb-2">
                        </div>
                    </fieldset>
                    <button class="btn btn-primary" type="submit">Save</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}