MedicalProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('auth_app.urls')),
    path('', include('patient_app.urls')),
]

auth_app/urls.py
from django.urls import path
from . import views

app_name = 'auth_app'
urlpatterns = [
    path('register/', views.patient_registration, name='registration'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

auth_app/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class MyUserManager(BaseUserManager):
    def create_user(self, username, password=None, **kwargs):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not username:
            raise ValueError("Users must have an email address")

        user = self.model(
            username=self.normalize_email(username),
            **kwargs
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            username,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    username = models.CharField(
        verbose_name="Username",
        max_length=255,
        unique=True,
    )
    name = models.CharField(max_length=100, null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    gender = models.CharField(null=True, blank=True, max_length=5)
    weight = models.FloatField(null=True, blank=True)
    height = models.FloatField(null=True, blank=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

auth_app/forms.py
from django import forms
from django.core.exceptions import ValidationError

class PatientRegistrationForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()
    name = forms.CharField(max_length=100)
    dob = forms.DateField()
    gender = forms.CharField()
    height = forms.IntegerField() # in centimeters
    weight = forms.IntegerField() # in kg

    def clean_password(self):
        pwd = self.cleaned_data['password']
        if not len(pwd) >= 8:
            raise ValidationError('Password length must be greater than or equal to 8. ')
        return pwd
    
    def clean_height(self):
        height = self.cleaned_data['height']
        if height >= 300:
            raise ValidationError('Height should not be greater than 10 feet.')
        return height
    
    def clean_weight(self):
        weight = self.cleaned_data['weight']
        if weight >= 200:
            raise ValidationError("Weight shouldn't be greater than 200kg")
        return weight
    

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_password(self):
        pwd = self.cleaned_data['password']
        if len(pwd) < 8:
            raise ValidationError('Password length should be greater than 8 characters.')
        return pwd

auth_app/views.py
from django.shortcuts import render
from .models import User
from .forms import PatientRegistrationForm, LoginForm
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth import login, authenticate, logout


def patient_registration(request):
    if request.method == "POST":
        form = PatientRegistrationForm(request.POST)
        if form.is_valid():
            try:
                User.objects.create_user(**form.cleaned_data)
                return redirect(reverse('auth_app:login'))
            except :
                return render(request, 'auth_app/registration.html', {'form':form, 'error':'Username Already taken'})
        else:
            return render(request, 'auth_app/registration.html', {'form':form})
    else:
        form = PatientRegistrationForm()
    return render(request, 'auth_app/registration.html', {'form':form})


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(**form.cleaned_data)
            if user is not None:
                login(request, user)
                return redirect(reverse('patient_app:data_entry'))
            else:
                error = "Invalid credentials"
                return render(request, 'auth_app/login.html', {'form':form,'error':error})
        else:
            return render(request, 'auth_app/login.html', {'form':form})
    form = LoginForm() 
    return render(request, 'auth_app/login.html', {'form':form})
        

def logout_view(request):
    logout(request)
    return redirect(reverse('auth_app:login'))

auth_app/templates/auth_app/login.html
{% extends 'base.html' %}

{% block body %}
    <div class="container-fluid">
        <div class="row justify-content-center h-30 align-items-center">
            {% if user.is_authenticated %}
                <div class="col h4">You have already logged in.</div>
            {% else %}
                <div class="col-md-4">
                    <form method="post">
                        {% csrf_token %}
                        <fieldset>
                            <legend class="text-white">Login to continue</legend>
                            {% if error %}
                                {{error}}
                            {% endif %}
                            {% if form.username.errors %}
                                {{form.username.errors}}
                            {% endif %}
                            <div class="mb-3">
                                <label for="id_username" class="form-label">Username</label>
                                <input type="text" id="id_username" placeholder="Enter username" name="username" class="form-control">
                            </div>
                            {% if form.password.errors %}
                                {{form.password.errors}}
                            {% endif %}
                            <div class="mb-3">
                                <label for="id_pwd" class="form-label">Password</label>
                                <input type="password" id="id_pwd" placeholder="Enter password" name="password" class="form-control">
                            </div>
                        </fieldset>
                        <button type="submit" class="btn btn-success">Login</button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

auth_app/templates/auth_app/registration.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <div class="row justify-content-center">
            {% if user.is_authenticated %}
                <div class="col h3">You have already registered</div>
            {% else %}
                <div class="col-md-6">
                    <form method="post">
                        {% csrf_token %}
                        <fieldset>
                            <legend class="text-white">Register Patient</legend>
                            {% if error %}
                                {{error}}
                            {% endif %}
                            {% if form.username.errors %}
                                {{form.username.errors}}
                            {% endif %}
                            <div class="mb-3">
                                <label for="id_username" class="form-label">Username</label>
                                <input type="text" id="id_username" name="username" class="form-control" placeholder="Enter your username" >
                            </div>
                            {% if form.password.errors %}
                                {{form.password.errors}}
                            {% endif %}
                            <div class="mb-3">
                                <label for="id_pwd" class="form-label">Password</label>
                                <input type="password" id="id_pwd" name="password" class="form-control" placeholder="Enter your password" >
                            </div>
                            {% if form.name.errors %}
                                {{form.name.errors}}
                            {% endif %}
                            <div class="mb-3">
                                <label for="id_name" class="form-label">Name</label>
                                <input type="text" id="id_name" name="name" class="form-control" placeholder="Enter you name">
                            </div>
                            {% if form.dob.errors %}
                                {{form.dob.errors}}
                            {% endif %}
                            <div class="mb-3">
                                <label for="id_dob" class="form-label">Date of Birth</label>
                                <input type="date" id="id_dob" name="dob" class="form-control">
                            </div>
                            {% if form.gender.errors %}
                                {{form.gender.errors}}
                            {% endif %}
                            <div class="mb-3">
                                <label for="id_gender" class="form-label">Gender</label>
                                <select name="gender" id="id_gender" class="form-select">
                                    <option selected>Select the gender</option>
                                    <option value1="M">Male</option>
                                    <option value="F">Female</option>
                                </select>
                            </div>
                            {% if form.height.errors %}
                                {{form.height.errors}}
                            {% endif %}
                            <div class="mb-3">
                                <label for="id_height" class="form-label">Height</label>
                                <input type="integer" id="id_height" name="height" class="form-control" placeholder="Enter height in cm" >
                            </div>
                            {% if form.weight.errors %}
                                {{form.weight.errors}}
                            {% endif %}
                            <div class="mb-3">
                                <label for="id_weight" class="form-label">Weight</label>
                                <input type="integer" id="id_weight" name="weight" class="form-control" placeholder="Enter weight in Kg" >
                            </div>
                        </fieldset>
                        <button class="btn btn-success" type="submit">Submit</button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}