MedicalProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('auth_app.urls')),
    path('', include('patient_app.urls')),
]

auth_app/urls.py
from django.urls import path
from . import views

app_name = 'auth_app'
urlpatterns = [
    path('register/', views.patient_registration, name='registration'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

patient_app/urls.py
from django.urls import path
from . import views


app_name = 'patient_app'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('patient/patient-data-entry/', views.patient_data_enter_view, name='data_entry'),
    path('patient/dashboard/', views.patient_dashboard, name='dashboard'),
]

auth_app/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class MyUserManager(BaseUserManager):
    def create_user(self, username, password=None, **kwargs):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not username:
            raise ValueError("Users must have an email address")

        user = self.model(
            username=self.normalize_email(username),
            **kwargs
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            username,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    username = models.CharField(
        verbose_name="Username",
        max_length=255,
        unique=True,
    )
    name = models.CharField(max_length=100, null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    gender = models.CharField(null=True, blank=True, max_length=5)
    weight = models.FloatField(null=True, blank=True)
    height = models.FloatField(null=True, blank=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

auth_app/forms.py
from django import forms
from django.core.exceptions import ValidationError

class PatientRegistrationForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()
    name = forms.CharField(max_length=100)
    dob = forms.DateField()
    gender = forms.CharField()
    height = forms.IntegerField() # in centimeters
    weight = forms.IntegerField() # in kg

    def clean_password(self):
        pwd = self.cleaned_data['password']
        if not len(pwd) >= 8:
            raise ValidationError('Password length must be greater than or equal to 8. ')
        return pwd
    
    def clean_height(self):
        height = self.cleaned_data['height']
        if height >= 300:
            raise ValidationError('Height should not be greater than 10 feet.')
        return height
    
    def clean_weight(self):
        weight = self.cleaned_data['weight']
        if weight >= 200:
            raise ValidationError("Weight shouldn't be greater than 200kg")
        return weight
    

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_password(self):
        pwd = self.cleaned_data['password']
        if len(pwd) < 8:
            raise ValidationError('Password length should be greater than 8 characters.')
        return pwd

auth_app/views.py
from django.shortcuts import render
from .models import User
from .forms import PatientRegistrationForm, LoginForm
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth import login, authenticate, logout


def patient_registration(request):
    if request.method == "POST":
        form = PatientRegistrationForm(request.POST)
        if form.is_valid():
            try:
                User.objects.create_user(**form.cleaned_data)
                return redirect(reverse('auth_app:login'))
            except :
                return render(request, 'auth_app/registration.html', {'form':form, 'error':'Username Already taken'})
        else:
            return render(request, 'auth_app/registration.html', {'form':form})
    else:
        form = PatientRegistrationForm()
    return render(request, 'auth_app/registration.html', {'form':form})


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(**form.cleaned_data)
            if user is not None:
                login(request, user)
                return redirect(reverse('patient_app:data_entry'))
            else:
                error = "Invalid credentials"
                return render(request, 'auth_app/login.html', {'form':form,'error':error})
        else:
            return render(request, 'auth_app/login.html', {'form':form})
    form = LoginForm() 
    return render(request, 'auth_app/login.html', {'form':form})
        

def logout_view(request):
    logout(request)
    return redirect(reverse('auth_app:login'))

auth_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Health Care</title>
    
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <style>
        .h-20{
            height: 20rem;
        }
        .h-30{
            height:30rem;
        }

        body{
            background-image:url(https://media.istockphoto.com/id/1391206326/vector/medical-equipment-3d-cartoon-style-vaccine-stethoscope-capsule-pills-and-medicine-box.jpg?s=612x612&w=0&k=20&c=inibDS_pfDwVN8EeGPmbuXcPo8wxL5OgKTX0zxiYsN0=);
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
        }
        .rating {
            unicode-bidi: bidi-override;
            direction: rtl;
            font-size: 25px;
        }
        .rating > span {
            display: inline-block;
            position: relative;
            width: 1.1em;
        }
        .rating > span:hover:before,
        .rating > span:hover ~ span:before {
            content: "\2605";
            position: absolute;
            
        }
        .custom-toggler .navbar-toggler-icon {
            color: red; /* Change color here */
        }
        .text-gold{
            color: gold;
        }
        
    </style>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-black">
        <div class="container-fluid">
            <a href="#" class="navbar-brand h1  text-white">Health Care</a>
            
            <div class="navbar-toggler bg-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" >
                <span class="navbar-toggler-icon" style="color: white;" ></span>
            </div>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="/admin/login/" class="nav-link text-white">Admin Panel</a>
                        </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'patient_app:dashboard' %}" class="nav-link text-white">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'patient_app:data_entry' %}" class="nav-link text-white">Health Data</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'auth_app:logout' %}" class="nav-link  text-white">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a href="{% url 'auth_app:registration' %}" class="nav-link  text-white">Register</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'auth_app:login' %}" class="nav-link text-white">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% if user.is_authenticated %}
        <div class="container text-white">
            <div class="row justify-content-start mt-3">
                <span class="h5">{{user.name}}</span>
            </div>
        </div>
    {% endif %}
    
    {% block body %}{% endblock %}
    

    <script src="https://cdn.jsdelivr.net/npm/jquery"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    
    
</body>
</html>